#!/bin/bash
set -ex
mkdir -p /var/www/html
rm -f /var/www/html/index.html
echo -en "<html>
    <head>
        <title>CowEnv</title>
    </head>
    <body>
        <pre>" > /var/www/html/index.html
printenv | /usr/local/bin/cowsay -W${COWSAY_W} -f${COWSAY_F} -n >> /var/www/html/index.html
echo -e "</pre>
    </body>
</html>" >> /var/www/html/index.html

/usr/sbin/nginx -c /etc/nginx/nginx.conf -g 'daemon off;' -p /var/www/run/nginx